services:
  my_db:
    image: mysql:8.0
    container_name: rpi_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: test_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - infra_net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot_password"]
      interval: 5s
      timeout: 5s
      retries: 5

  my_redis:
    image: redis:7-alpine
    container_name: rpi_redis
    ports:
      - "6379:6379"
    networks:
      - infra_net

  # 你的 Python 核心服务
  my_script_service:
    build: ./backend
    container_name: rpi_python_app
    ports:
      - "8501:8501" # Streamlit 默认端口
    environment:
      - SPRING_DATASOURCE_URL=my_db
      - SPRING_REDIS_HOST=my_redis
    depends_on:
      my_db:
        condition: service_healthy
      my_redis:
        condition: service_started
    networks:
      - infra_net

volumes:
  mysql_data:

networks:
  infra_net:
    driver: bridge
